app:
    resource: "@CoreBundle/Controller/DefaultController.php"
    type:     rest
    prefix:   api

user:
    resource: "@UserBundle/Controller/UserController.php"
    type:     rest
    prefix:   user