security:
  encoders:
      UserBundle\Entity\User: bcrypt

  providers:
    core_user_provider:
      id: core_user_provider

  firewalls:
    dev:
        pattern:  ^/(_(profiler|wdt)|css|images|js)/
        security: false

    main:
      pattern:    ^/api
      stateless: true
      provider: core_user_provider
      simple_preauth:
        authenticator: core_user_authenticator