security:
  role_hierarchy:
      ROLE_ADMIN:       ROLE_USER
      ROLE_SUPER_ADMIN: ROLE_ADMIN

  encoders:
      UserBundle\Entity\User: bcrypt

  providers:
    user.user.provider:
      id: user.user.provider

  firewalls:
    dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false

    auth:
      pattern: ^/api/auth
      stateless: true
      security: false

    api:
      pattern: ^/api
      stateless: true
      provider: user.user.provider
      simple_preauth:
        authenticator: user.user.authenticator