security:
  role_hierarchy:
      ROLE_ADMIN:       ROLE_USER
      ROLE_SUPER_ADMIN: ROLE_ADMIN

  encoders:
      UserBundle\Entity\User: bcrypt

  providers:
    core.user_provider:
      id: core.user_provider

  firewalls:
    dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false

    api:
      pattern: ^/api
      stateless: true
      provider: core.user_provider
      simple_preauth:
        authenticator: core.user_authenticator

    auth:
      pattern: ^/auth
      stateless: true
      security: false