api_store_controller:
    resource: '@ApiBundle/Controller/ScreenController.php'
    prefix: stores
    type: rest

api_user_controller:
    resource: '@ApiBundle/Controller/UserController.php'
    prefix: user
    type: rest

api_auth_controller:
    resource: '@ApiBundle/Controller/AuthController.php'
    prefix: auth
    type: rest