services:
  core_user_provider:
    class: UserBundle\Security\UserProvider
    arguments: ['@doctrine.orm.entity_manager']

  core_user_authenticator:
    class: UserBundle\Security\UserAuthenticator

  core_user_manager:
    class: UserBundle\Security\UserManager
    arguments: ['@doctrine.orm.entity_manager', '@security.password_encoder']