services:
  manage_user_provider:
    class: UserBundle\Security\UserProvider
    arguments: ['@doctrine.orm.entity_manager']

  manage_user_authenticator:
    class: UserBundle\Security\UserAuthenticator

  manage_user_manager:
    class: UserBundle\Security\UserManager
    arguments: ['@doctrine.orm.entity_manager', '@security.password_encoder']