services:
    user.user_provider:
        class: UserBundle\Security\UserProvider
        arguments: ['@doctrine.orm.entity_manager']

    user.user_authenticator:
        class: UserBundle\Security\UserAuthenticator

    user.user_manager:
        class: UserBundle\Security\UserManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.password_encoder'
            - '@core.mailer.manager'